/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class BucketDetails {
  name: string
  location: string
}
export class S3OpsRust {
  constructor()
  listBuckets(): Array<BucketDetails>
}
