/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BucketDetails {
  name: string
  location: string
}
export function sign(host: string, url: string): Promise<string>
export class S3OpsRust {
  constructor()
  listBuckets(): Array<BucketDetails>
}
