AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Manage your S3 buckets

Globals:
  Function:
    Timeout: 10
    Layers: 
      - arn:aws:lambda:us-east-1:234138278568:layer:analytics-extension:8
    Environment:
        Variables:
          ANALYTICS_SQS_URL: !Ref AnalyticsSQS

Resources:
  RootApiRust:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerRust.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization
  RootApiPython:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerPython.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization

  AuthorizerPython:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer_python/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: auth
          LOG_LEVEL: INFO
          USERS_TABLE_NAME: !Ref UsersTable
      Architectures:
        - x86_64
  AuthorizerRust:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda 
    Properties:
      CodeUri: ./authorizer_rust 
      Handler: bootstrap
      Runtime: provided.al2
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
      Architectures:
        - x86_64

  ListBucketsPython:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list_buckets_python/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
              Resource: "*"
      Architectures:
        - x86_64
      Events:
        ListBcuketsPython:
          Type: Api
          Properties:
            RestApiId: !Ref RootApiPython
            Path: /buckets-python
            Method: get

  ListBucketsNode:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list-buckets-node/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
              Resource: "*"
      Architectures:
        - x86_64
      Events:
        ListBucketsNode:
          Type: Api
          Properties:
            RestApiId: !Ref RootApiPython
            Path: /buckets-node
            Method: get

  ListBucketsRustNode:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list-buckets-rust-node/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
              Resource: "*"
      Architectures:
        - x86_64
      Events:
        ListBucketsRustNode:
          Type: Api
          Properties:
            RestApiId: !Ref RootApiRust
            Path: /buckets-rust-node
            Method: get
  

  ListBucketsRustPython:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list_buckets_rust_python/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
              Resource: "*"
      Architectures:
        - x86_64
      Events:
        ListBucketsRustPython:
          Type: Api
          Properties:
            RestApiId: !Ref RootApiRust
            Path: /buckets-rust-python
            Method: get

  GetS3Details:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-s3-details-node/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnalyticsSQS.QueueName
      Events:
        GetS3Details:
          Type: Api
          Properties:
              RestApiId: !Ref RootApiRust
              Path: /get-bucket
              Method: get

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  AnalyticsSQS:
    Type: AWS::SQS::Queue
       
Outputs:
  S3AdminApiListNode:
    Value: !Sub "curl -u 'admin:CTax;#+9+X3T%|z' https://${RootApiPython}.execute-api.${AWS::Region}.amazonaws.com/Prod/buckets-node"
  S3AdminApiListPython:
    Value: !Sub "curl -u 'admin:CTax;#+9+X3T%|z' https://${RootApiPython}.execute-api.${AWS::Region}.amazonaws.com/Prod/buckets-python"
  S3AdminApiListRust:
    Value: !Sub "curl -u 'admin:CTax;#+9+X3T%|z' https://${RootApiRust}.execute-api.${AWS::Region}.amazonaws.com/Prod/buckets-rust-python"
  S3AdminApiListNodeRust:
    Value: !Sub "curl -u 'admin:CTax;#+9+X3T%|z' https://${RootApiRust}.execute-api.${AWS::Region}.amazonaws.com/Prod/buckets-rust-node"
  GetS3DetailsNode:
    Value: !Sub "curl -u 'admin:CTax;#+9+X3T%|z' https://${RootApiRust}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-bucket"
  DynamoDB:
    Value: !Sub "aws dynamodb put-item --table-name ${UsersTable} --item '{\"user\": {\"S\": \"admin\"}, \"password\": {\"S\": \"CTax;#+9+X3T%|z\"}}' --return-consumed-capacity TOTAL"
