AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Manage your S3 buckets

Globals:
  Function:
    Timeout: 10

Resources:
  AdminPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        PasswordLength: 16
        ExcludeCharacters: ":"
  RootApiRust:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerRust.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization
  RootApiPython:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerPython.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization

  AuthorizerPython:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer_python/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref AdminPasswordSecret
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: auth
          LOG_LEVEL: INFO
          SECRETAUTH_PARAM_NAME: !Ref AdminPasswordSecret
      Architectures:
        - x86_64
  AuthorizerRust:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda 
    Properties:
      CodeUri: ./authorizer_rust 
      Handler: bootstrap
      Runtime: provided.al2
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref AdminPasswordSecret
      Environment:
        Variables:
          SECRETAUTH_PARAM_NAME: !Ref AdminPasswordSecret
      Architectures:
        - x86_64
  ListBucketsPython:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list_buckets_python/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
              Resource: "*"
      Architectures:
        - x86_64
      Events:
        ListBcuketsPython:
          Type: Api
          Properties:
            RestApiId: !Ref RootApiPython
            Path: /buckets-python
            Method: get

  ListBucketsRust:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list_buckets_rust/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetBucketLocation
              Resource: "*"
      Architectures:
        - x86_64
      Events:
        ListBcuketsRust:
          Type: Api
          Properties:
            RestApiId: !Ref RootApiRust
            Path: /buckets-rust
            Method: get

Outputs:
  S3AdminApiListPython:
    Value: !Sub "curl -u 'admin:<your pass>' https://${RootApiPython}.execute-api.${AWS::Region}.amazonaws.com/Prod/buckets-python"
  S3AdminApiListRust:
    Value: !Sub "curl -u 'admin:<your pass>' https://${RootApiRust}.execute-api.${AWS::Region}.amazonaws.com/Prod/buckets-rust"
  PasswordSecretURL:
    Value: !Sub "https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=${AdminPasswordSecret}"
